extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679
  query:
    protocols:
      http:
        endpoint: 0.0.0.0:18888
      grpc:
        endpoint: 0.0.0.0:18889
    storage:
      clickhouse:
        dsn: tcp://default:changeme@localhost:9000/openinsight
        tls:
          insecure: true
          insecure_skip_verify: true
        logging_table_name: openinsight_logs
        tracing_table_name: openinsight_traces
        metrics_table_name: openinsight_metrics
    tracing_query:
      storage_type: clickhouse
    logging_query:
      storage_type: clickhouse
    metrics_query:
      storage_type: clickhouse

receivers:
  otlp:
    protocols:
      grpc:
      http:

  opencensus:

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

processors:
  batch:

exporters:
  logging:
    logLevel: debug
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1
  clickhouse:
    dsn: tcp://default:changeme@localhost:9000/openinsight
    logs_table_name: openinsight_logs
    traces_table_name: openinsight_traces
    timeout: 10s
    sending_queue:
      queue_size: 100
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

service:
  pipelines:
    traces:
      receivers: [otlp, opencensus, jaeger, zipkin]
      processors: [batch]
      exporters: [ clickhouse ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ clickhouse ]
  extensions: [pprof, zpages, query, health_check]