extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679
  query:
    protocols:
      http:
        endpoint: 0.0.0.0:18888
      grpc:
        endpoint: 0.0.0.0:18889
    storage:
      elasticsearch:
        endpoints: [ "https://10.6.229.192:31450" ]
        traces_index: otlp_spans
        user: elastic
        password: XAlJ948ZY0leE320SQ6hfv17
      clickhouse:
        dsn: tcp://127.0.0.1:9000?database=default
        ttl_days: 3
        timeout: 5s
    tracing_query:
      storage_type: elasticsearch
    logging_query:
      storage_type: elasticsearch
    metrics_query:
      storage_type: elasticsearch

receivers:
  otlp:
    protocols:
      grpc:
      http:

  opencensus:

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

processors:
  batch:

exporters:
  logging:
    logLevel: debug
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1
  elasticsearch/trace:
    tls:
      insecure: false
      insecure_skip_verify: true
    endpoints: [https://10.6.229.192:31450]
    timeout: 2m
    traces_index: otlp_spans
    user: elastic
    password: XAlJ948ZY0leE320SQ6hfv17
    retry:
      max_requests: 5

service:

  pipelines:

    traces:
      receivers: [otlp, opencensus, jaeger, zipkin]
      processors: [batch]
      exporters: [logging,elasticsearch/trace]

    metrics:
      receivers: [otlp, opencensus, prometheus]
      processors: [batch]
      exporters: [logging]

  extensions: [health_check, query, pprof, zpages]