version: "2"
services:
  clickhouse:
    image: docker.io/bitnami/clickhouse:22.9
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_ADMIN_PASSWORD=changeme
      - TZ=UTC
    ports:
      - '8123:8123'
    volumes:
      - ./scripts/my_init_script.sh:/docker-entrypoint-initdb.d/my_init_script.sh
      - clickhouse_data:/bitnami/clickhouse
  # Collector
  openinsight:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    restart: always
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "18888:18888" # query extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - clickhouse

#  demo-client:
#    build:
#      dockerfile: Dockerfile
#      context: ./client
#    environment:
#      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
#      - DEMO_SERVER_ENDPOINT=http://demo-server:7080/hello
#    depends_on:
#      - demo-server

#  demo-server:
#    build:
#      dockerfile: Dockerfile
#      context: ./server
#    environment:
#      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
#    ports:
#      - "7080"
#    depends_on:
#      - otel-collector

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

volumes:
  clickhouse_data:
    driver: local